from django.urls import path
from . import views

urlpatterns = [
    path('',views.home, name='home'),
    path('regions_form/', views.regions_form, name='regions_form'), 
    path('regions_list/', views.region_list, name='regions_list'),
    path('regions_update/<int:pk>/', views.regions_update, name='regions_update'),
    path('regions_delete/<int:pk>/', views.regions_delete, name='regions_delete'),
    path('villes_form/', views.villes_form, name='villes_form'),    
    path('villes_list/', views.ville_list, name='villes_list'),
    path('villes_update/<int:pk>/', views.villes_update, name='villes_update'),
    path('villes_delete/<int:pk>/', views.villes_delete, name='villes_delete'),
    path('stations_form/', views.station_form, name='stations_form'),
    path('stations_list/', views.station_list, name='stations_list'),
    path('stations_update/<int:pk>/', views.stations_update, name='stations_update'),
    path('stations_delete/<int:pk>/', views.stations_delete, name='stations_delete'),
    path('alerts_form/', views.alerts_form, name='alerts_form'),
    path('alerts_list/', views.alerts_list, name='alerts_list'),
    path('alerts_update/<int:pk>/', views.alerts_update, name='alerts_update'),
    path('alerts_delete/<int:pk>/', views.alerts_delete, name='alerts_delete'),
    path('agents_form/', views.agents_form, name='agents_form'),
    path('agents_list/', views.agents_list, name='agents_list'),
    path('agents_update/<str:pk>/', views.agents_update, name='agents_update'),
    path('agents_delete/<str:pk>/', views.agents_delete, name='agents_delete'),
    path('mesures_form/', views.mesures_form, name='mesures_form'),
    path('mesures_list/', views.mesures_list, name='mesures_list'),
    path('mesures_update/<str:pk>/', views.mesures_update, name='mesures_update'), 
    path('mesures_delete/<str:pk>/', views.mesures_delete, name='mesures_delete'),
    path('consulter_list/', views.consulter_list, name='consulter_list'),
    path('consulter_form/', views.consulter_form, name='consulter_form'),
    path('consulter_delete/<str:station_pk>/<str:previsionniste_pk>/',views.consulter_delete,name='consulter_delete'),
    path('consulter_update/<str:station_pk>/<str:previsionniste_pk>/',views.consulter_update,name='consulter_update'),
    path('previsionnistes_list/', views.previsionnistes_list, name='previsionnistes_list'),
    path('previsionnistes_form/', views.previsionnistes_form, name='previsionnistes_form'),
    path('previsionnistes_update/<str:pk>/', views.previsionnistes_update, name='previsionnistes_update'),
    path('previsionnistes_delete/<str:pk>/', views.previsionnistes_delete, name='previsionnistes_delete'),
    path("statistiques/", views.statistiques, name="statistiques"),
    path('statistiques/telecharger/', views.telecharger_rapport, name='telecharger_rapport'),

]