# Generated by Django 6.0 on 2025-12-06 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentMeteorologique',
            fields=[
                ('cin', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='CIN')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=50, verbose_name='Prénom')),
                ('age', models.SmallIntegerField(verbose_name='Âge')),
                ('salaire', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Salaire')),
            ],
            options={
                'verbose_name': 'Agent Météorologique',
                'verbose_name_plural': 'Agents Météorologiques',
            },
        ),
        migrations.CreateModel(
            name='Previsionniste',
            fields=[
                ('cin', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='CIN')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=50, verbose_name='Prénom')),
            ],
            options={
                'verbose_name': 'Prévisionniste',
                'verbose_name_plural': 'Prévisionnistes',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True, verbose_name='Nom de la Région')),
                ('nombre_des_villes', models.IntegerField(default=0, verbose_name='Nombre de Villes')),
                ('densite_de_population', models.IntegerField(verbose_name='Densité de Population')),
                ('taille', models.FloatField(verbose_name='Taille (Surface)')),
            ],
            options={
                'verbose_name': 'Région',
                'verbose_name_plural': 'Régions',
            },
        ),
        migrations.CreateModel(
            name='StationMeteorologique',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False, verbose_name='Code de la Station')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom de la Station')),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Latitude')),
                ('longtitude', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Longitude')),
                ('altitude', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Altitude')),
                ('type', models.CharField(max_length=50, verbose_name='Type de Station')),
            ],
            options={
                'verbose_name': 'Station Météo',
                'verbose_name_plural': 'Stations Météo',
            },
        ),
        migrations.CreateModel(
            name='Consulter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previsionniste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.previsionniste')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.stationmeteorologique')),
            ],
            options={
                'verbose_name': 'Consultation de Station',
                'verbose_name_plural': 'Consultations de Stations',
                'unique_together': {('station', 'previsionniste')},
            },
        ),
        migrations.AddField(
            model_name='previsionniste',
            name='stations_consultées',
            field=models.ManyToManyField(related_name='previsionnistes_consultants', through='home.Consulter', to='home.stationmeteorologique'),
        ),
        migrations.CreateModel(
            name='MesureMeteorologique',
            fields=[
                ('id_mesure', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID de la Mesure')),
                ('date_heure', models.DateTimeField(verbose_name='Date et Heure de la Mesure')),
                ('temperature_moyenne', models.IntegerField(verbose_name='Température Moyenne')),
                ('temperature_maximale', models.IntegerField(verbose_name='Température Maximale')),
                ('temperature_minimale', models.IntegerField(verbose_name='Température Minimale')),
                ('taux_d_humidité', models.FloatField(verbose_name="Taux d'Humidité")),
                ('vitesse_du_vent', models.FloatField(verbose_name='Vitesse du Vent')),
                ('quantite_de_precipation', models.IntegerField(verbose_name='Quantité de Précipitation')),
                ('pression_atmospherique', models.FloatField(verbose_name='Pression Atmosphérique')),
                ('direction_du_vent', models.CharField(max_length=50, verbose_name='Direction du Vent')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mesures_prises', to='home.agentmeteorologique', verbose_name='Agent Météo')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mesures', to='home.stationmeteorologique', verbose_name='Station de mesure')),
            ],
            options={
                'verbose_name': 'Mesure Météorologique',
                'verbose_name_plural': 'Mesures Météorologiques',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField(verbose_name="Date et Heure de l'Alerte")),
                ('type', models.CharField(max_length=50, verbose_name="Type d'Alerte")),
                ('zone_cocernee', models.CharField(max_length=50, verbose_name='Zone Concernée')),
                ('niveau_de_gravite', models.CharField(max_length=50, verbose_name='Niveau de Gravité')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='home.stationmeteorologique', verbose_name='Station émettrice')),
            ],
            options={
                'verbose_name': 'Alerte',
                'verbose_name_plural': 'Alertes',
            },
        ),
        migrations.AddField(
            model_name='agentmeteorologique',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='home.stationmeteorologique', verbose_name="Station d'affectation"),
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom de la Ville')),
                ('suface', models.FloatField(verbose_name='Surface')),
                ('densite_population', models.IntegerField(verbose_name='Densité de Population')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villes', to='home.region', verbose_name='Région associée')),
            ],
            options={
                'verbose_name': 'Ville',
                'verbose_name_plural': 'Villes',
            },
        ),
        migrations.AddField(
            model_name='stationmeteorologique',
            name='ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='home.ville', verbose_name='Ville associée'),
        ),
    ]
