# Generated by Django 6.0 on 2025-12-07 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='region',
            table='region',
        ),
    ]
