# Generated by Django 6.0 on 2025-12-07 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_region_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['nom'], 'verbose_name': 'Région', 'verbose_name_plural': 'Régions'},
        ),
        migrations.AlterModelOptions(
            name='stationmeteorologique',
            options={'verbose_name': 'Station Météorologique', 'verbose_name_plural': 'Stations Météorologiques'},
        ),
        migrations.RemoveField(
            model_name='alert',
            name='id',
        ),
        migrations.RemoveField(
            model_name='region',
            name='id',
        ),
        migrations.RemoveField(
            model_name='ville',
            name='id',
        ),
        migrations.AddField(
            model_name='alert',
            name='id_alerte',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID Alerte'),
        ),
        migrations.AddField(
            model_name='region',
            name='id_region',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID Région'),
        ),
        migrations.AddField(
            model_name='ville',
            name='id_ville',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID Ville'),
        ),
        migrations.AlterField(
            model_name='consulter',
            name='previsionniste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.previsionniste', verbose_name='Prévisionniste'),
        ),
        migrations.AlterField(
            model_name='consulter',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.stationmeteorologique', verbose_name='Station'),
        ),
        migrations.AlterField(
            model_name='mesuremeteorologique',
            name='date_heure',
            field=models.DateTimeField(verbose_name='Date et Heure'),
        ),
        migrations.AlterField(
            model_name='previsionniste',
            name='stations_consultées',
            field=models.ManyToManyField(related_name='previsionnistes_consultants', through='home.Consulter', to='home.stationmeteorologique', verbose_name='Stations consultées'),
        ),
        migrations.AlterModelTable(
            name='agentmeteorologique',
            table='agent_meteorologique',
        ),
        migrations.AlterModelTable(
            name='alert',
            table='alert',
        ),
        migrations.AlterModelTable(
            name='consulter',
            table='consulter',
        ),
        migrations.AlterModelTable(
            name='mesuremeteorologique',
            table='mesure_meteorologique',
        ),
        migrations.AlterModelTable(
            name='previsionniste',
            table='previsionnistes',
        ),
        migrations.AlterModelTable(
            name='stationmeteorologique',
            table='station_meteorologique',
        ),
        migrations.AlterModelTable(
            name='ville',
            table='ville',
        ),
    ]
