# Generated by Django 6.0 on 2025-12-08 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_region_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ville',
            name='region',
            field=models.ForeignKey(db_column='id_region', on_delete=django.db.models.deletion.CASCADE, related_name='villes', to='home.region', verbose_name='Région associée'),
        ),
    ]
