# Generated by Django 6.0 on 2025-12-08 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_ville_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmeteorologique',
            name='date_embauche',
            field=models.DateField(default='1999-01-01', verbose_name="Date d'embauche"),
            preserve_default=False,
        ),
    ]
