# Generated by Django 6.0 on 2025-12-08 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_agentmeteorologique_date_embauche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentmeteorologique',
            name='station',
            field=models.ForeignKey(db_column='code', on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='home.stationmeteorologique', verbose_name="Station d'affectation"),
        ),
    ]
