# Generated by Django 6.0 on 2025-12-08 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_agentmeteorologique_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationmeteorologique',
            name='ville',
            field=models.ForeignKey(db_column='id_ville', on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='home.ville', verbose_name='Ville associée'),
        ),
    ]
