# Generated by Django 6.0 on 2025-12-08 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_mesuremeteorologique_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesuremeteorologique',
            name='station',
            field=models.ForeignKey(blank=True, db_column='code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mesures', to='home.stationmeteorologique', verbose_name='Station de mesure'),
        ),
    ]
