# Generated by Django 6.0 on 2025-12-08 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_mesuremeteorologique_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulter',
            name='previsionniste',
            field=models.ForeignKey(db_column='cin', on_delete=django.db.models.deletion.CASCADE, to='home.previsionniste', verbose_name='Prévisionniste'),
        ),
        migrations.AlterField(
            model_name='consulter',
            name='station',
            field=models.ForeignKey(db_column='code', on_delete=django.db.models.deletion.CASCADE, to='home.stationmeteorologique', verbose_name='Station'),
        ),
    ]
