# Generated by Django 6.0 on 2025-12-09 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_consulter_previsionniste_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulter',
            options={'managed': False, 'verbose_name': 'Consultation de Station', 'verbose_name_plural': 'Consultations de Stations'},
        ),
    ]
